name: Python CI with uv

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'  # or your required version

      - name: Install uv
        run: |
          curl -Ls https://astral.sh/uv/install.sh | bash
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      
      - name: Create virtual environment
        run: uv venv

      - name: Install dependencies with uv
        run: uv pip install -r requirements.txt || uv pip install . #rewrote req file
